name: CI
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: '11.x'
    - uses: actions/cache@v1
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: mvn test
      run: |
        set -e
        ./mvnw -V test
    - name: mvn package
      if: github.ref == 'refs/heads/master'
      run: |
        set -e
        ./mvnw -V package -Dmaven.test.skip=true
    - uses: jvalkeal/setup-cf-cli@v0
      if: github.ref == 'refs/heads/master'
      with:
        version: 6.51.0        
    - name: cf push
      if: github.ref == 'refs/heads/master'
      env:
        CF_API: ${{ secrets.CF_API }}
        CF_USERNAME: ${{ secrets.CF_USERNAME }}
        CF_PASSWORD: ${{ secrets.CF_PASSWORD }}
        CF_ORG: ${{ secrets.CF_ORG }}
        CF_SPACE: ${{ secrets.CF_SPACE }}
      run: |
        set -e
        cf login -a ${CF_API} -u ${CF_USERNAME} -p ${CF_PASSWORD} -o ${CF_ORG} -s ${CF_SPACE}
        cf push --var push="$(date)"
